- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.agignore:
    ~/.aria2/aria2.conf:
    ~/.bash:
    ~/.bash_profile:
    ~/.bashrc:
#    ~/.dotfiles: ''
    ~/.emacs.d:
    ~/.emacs:
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.gnupg/gpg.conf:
    ~/.inputrc:
    ~/.screenrc:
    ~/.shell:
    ~/.tmux.conf:


- shell:
  - git update-submodules # after linking ~/.gitconfig
